rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
- pattern: master
  isAdminEnforced: true
  requiredStatusCheckContexts:
    - 'Kokoro'
    - 'ci/circleci: unit-python2.7'
    - 'ci/circleci: unit-python3.5'
    - 'ci/circleci: unit-python3.6'
    - 'ci/circleci: unit-python3.7'
    - 'cla/google'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
permissionRules:
  - team: actools
    permission: admin
